name: cat_alarm
description: A new Flutter project.
publish_to: 'none'
version: 1.0.5+15

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.39
  audio_session: ^0.1.16
  audioplayers: ^6.0.0
  flutter_localizations:
    sdk: flutter
  wakelock_plus: ^1.4.0
  screen_brightness: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  import_lint: ^1.0.1   # <-- statt ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/icons/catalarm.png
  generate: true
